version: "3.9"

services:
  oracle-container:
    shm_size: 8g
    container_name: oracle-database-${ORACLE_EDITION}
    image: container-registry.oracle.com/database/${ORACLE_EDITION}:${ORACLE_VERSION}
    env_file:
      - .env
    ports:
      - "${ORACLE_HOST_PORT}:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-dbs:/opt/oracle/homes
      # - oracle-product:/opt/oracle/product

    # healthcheck:
    #   test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

volumes:
  oracle-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ORACLE_DATA}
  oracle-dbs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ORACLE_HOMES}

